config/routes.rb
Surfeitalpha::Application.routes.draw do

  get "pages/current"

  get '/' => 'home#index', :as => :index

  get '/sessions/login' => 'sessions#login', :as => :login
  post '/sessions/create' => 'sessions#create_surfeit'
  match 'auth/:provider/callback', to: 'sessions#create_twitter'
  get '/sessions/logout' => 'sessions#destroy', :as => :logout
  get '/sessions/fail' => 'sessions#fail', :as => :fail


  resources :users
  

    # root :to => 'Directors#index'  DO THIS
 
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :username

  has_secure_password

  validates_presence_of :name, :email, :username

  validates_uniqueness_of :email, :username

  def self.from_omniauth(auth)
	where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
	
end

	def self.create_from_omniauth(auth)

		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["name"]
		end
		
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

    helper_method :current_user

  private

  def current_user

		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController


def index



end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def current
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def login
	
		
	end
	
	def create_twitter
		user = User.from_omniauth (env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to index_url, notice: "Signed In!"
	end


	  def auth_hash
    request.env['omniauth.auth']
  		end



	def create_surfeit

	 user = User.find_by_email(params[:email])
    
   		 if user != nil && user.authenticate(params[:password])
   		   session[:user_id] = user.id
   		   redirect_to index_url, :notice => "Welcome back, #{user.name}!"
   		 else
   		   redirect_to fail_url, :notice => "Sorry, try again."
   		 end
	end



	def destroy
	
		session[:user_id] = nil
    	redirect_to index_url

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1>INDEX</h1>
 
 <% if session[:user_id] != nil %>
 <% user = User.find_by_id(session[:user_id]).name %>
  
<% else %>
 Don't have an account? <%= link_to "Create an Account", new_user_url%>
 <br>
 <br>
 Are you an <em>awesome</em> Surfeit user? 

 <%= form_tag "/sessions/create" do %>

  
  <%= label_tag :email, "Email:" %>
  <%= text_field_tag :email %> <br>
  <%= label_tag :password, "Password:" %>
  <%= password_field_tag :password %><br>

  <%= submit_tag "Login"%>

<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Surfeitalpha</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	 <ul>
  </ul>
  <nav>
    <%= link_to "Sign in with Twitter", "/auth/twitter"%>
    <%= link_to "Home", index_url %> |
    
    <% if session[:user_id] == nil   # no one is logged in  %>
      <%= link_to "Sign In", login_url %>
    <% else # someone is logged in %>
      <%= link_to "Account", index_url %> |
      <%= User.find_by_id(session[:user_id]).name %>
      <%= link_to 'Sign Out', logout_path %>
    <% end %>
  </nav>
  <p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>
 

app/views/pages/current.html.erb
<h1>Pages#current</h1>
<p>Find me in app/views/pages/current.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :username, "Username:" %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email, "Email:" %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password:" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email_opt_in, "Email Updates:" %>
    <%= f.check_box :email_opt_in %>
  </div>
  <div class="actions">
    <%= f.submit "Join Us" %>
  </div>
<% end %> 

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>
<%= link_to 'Back', movies_url %>

app/views/users/index.html.erb
<h1> THE CURRENT </h1>

<table>
	<tr>
	  <th>Name</th>
	  <th>Email</th>
	  <th>Username</th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>
	
<% @users.each do |user| %>
	<tr>
	  <td><%= user.name %></td>
	  <td><%= user.email %></td>
	  <td><%= user.username %></td>
	  <td><%= link_to 'show' %></td>
	  <td><%= link_to 'edit'  %></td>
	  <td><%= link_to 'destroy' %></td>
	 	
	 </tr>
	<% end %>
</table>

<br />

 

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1> USER PAGE </h1>

Welcome, <%= User.find_by_id(session[:user_id]) %>